// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmyjmialucyixditgbqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteWptaWFsdWN5aXhkaXRnYnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTM3OTYsImV4cCI6MjA2ODg2OTc5Nn0.7C-lOCw1OvpQmTia-oTXA-mxSB9sUbtqW0paq3r-ZpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});